spring:
  application:
    name: rabbitmq-topic-consumer
  rabbitmq:
    port: 5672
    host: 127.0.0.1
    username: guest
    password: guest

# 设置交换器名称
mq.config.exchange: log.topic

# info队列名称
mq.config.queue.info: log.info
# error队列名称
mq.config.queue.error: log.error
# log队列名称
mq.config.queue.logs: log.all