spring:
  application:
    name: rabbitmq-ack-consumer
  rabbitmq:
    port: 5672
    host: 127.0.0.1
    username: guest
    password: guest
    listener:
#      direct:
#        retry:
#          enabled: true   # 开启重试
#          max-attempts: 3 # 最大重试次数
      simple:
        retry:
          enabled: true   # 开启重试
          max-attempts: 5 # 最大重试次数

# 设置交换器名称
mq.config.exchange: log.direct

# info队列名称
mq.config.queue.info: log.info
# info路由键
mq.config.queue.info.routing.key: log.info.routing.key

# error队列名称
mq.config.queue.error: log.error
# error路由键
mq.config.queue.error.routing.key: log.error.routing.key
